os: osx

before_install:
  - brew update
  - brew --env
  - brew config

install:
  - mkdir -p $(brew --repo)/Library/Taps/jad340
  - ln -s $PWD $(brew --repo)/Library/Taps/jad340/homebrew-repo
  - brew tap --repair

env:
  - TYPE=FORMULA PACKAGE=cgo
  - TYPE=CASK PACKAGE=nowplaying

script:
  - brew audit --strict $PACKAGE
  - if [ "$TYPE" = "FORMULA" ]; then brew install $PACKAGE && brew test $PACKAGE; fi
  - if [ "$TYPE" = "CASK" ]; then brew cask install $PACKAGE; fi

notifications:
  email:
    on_success: never
    on_failure: always
